server:
  port: 9006
  tomcat:
    threads:
      max: 10

management:
  health:
    elasticsearch:
        enabled: false
  endpoints:
    web.exposure:
      include: "*"

fhir:
  server:
    name: openEHR Services
    baseUrl: https://3cdzg7kbj4.execute-api.eu-west-2.amazonaws.com/poc/events
    version: 6.8.0
    authorize: https://launch.smarthealthit.org/v/r4/auth/authorize
    token: https://launch.smarthealthit.org/v/r4/auth/token
    introspect: https://launch.smarthealthit.org/v/r4/auth/introspect
    smart: true


