server:
  port: 9006
  tomcat:
    threads:
      max: 10

management:
  health:
    elasticsearch:
        enabled: false
  endpoints:
    web.exposure:
      include: "*"

fhir:
  server:
    name: openFHIR (openEHR to FHIR)
    baseUrl: http://localhost:9006
    version: 6.8.0
    authorize: https://launch.smarthealthit.org/v/r4/auth/authorize
    token: https://launch.smarthealthit.org/v/r4/auth/token
    introspect: https://launch.smarthealthit.org/v/r4/auth/introspect
    smart: true


